<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>ServiceBusThroughputTest.Common</RootNamespace>
    <AssemblyName>ServiceBusThroughputTest.Common</AssemblyName>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>