<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>ServiceBusThroughputTestLib</RootNamespace>
    <AssemblyName>ServiceBusThroughputTestLib</AssemblyName>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.15.0" />
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ServiceBusThroughputTest.Common/ServiceBusThroughputTest.Common.csproj" />
  </ItemGroup>
</Project>