<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ServiceBusThroughputTest</RootNamespace>
    <AssemblyName>ServiceBusThroughputTest</AssemblyName>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ServiceBusThroughputTest.Common/ServiceBusThroughputTest.Common.csproj" />
    <ProjectReference Include="../ServiceBusThroughputTestLib/ServiceBusThroughputTestLib.csproj" />
  </ItemGroup>
</Project>